# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-13 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date_added', models.DateField(default=datetime.datetime(2017, 2, 13, 9, 6, 27, 901652))),
                ('image', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
