# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-13 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 2, 13, 10, 29, 26, 870415)),
        ),
    ]
