# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-14 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20170213_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
